### ISSUE TITLE
[REQUEST] Distributed data parallel training

### ISSUE THREAD

**Issue by sangkeun00** [leopard-ai/betty#2]
Currently, Betty only supports torch.nn.DataParallel. Compared to torch.nn.parallel.DistributedDataParallel, torch.nn.DataParallel is much slower even in the single-machine multi-gpu settings. Therefore, we need to replace torch.nn.DataParallel with torch.nn.parallel.DistributedDataParallel for better training speed and the multi-machine multi-gpu support.

**Comment by gongbudaizhe** [comment]
can't agree more!

**Comment by gongbudaizhe** [comment]
I understand the difficulty of implementing this feature, but in my opinion, this is the single most important feature that betty should have while similar repos like https://github.com/facebookresearch/higher doesn't. To make GML/MLO more impactful, it should be applied to large scale problems in the wild. Distributed training is a must have for real applications.

The ad-hoc option looks good to me, can't wait to try it 👍

**Comment by sangkeun00** [comment]
Hello @gongbudaizhe, 

I apologize for the late reply! I finally implemented the distributed training feature for the multi-node/multi-gpu setting.
To try this feature, you should install the nightly version by directly cloning the most recent commit as:
```bash
git clone https://github.com/leopard-ai/betty.git
pip install betty
```
In detail, you can enable distributed training by 1) setting `distributed=True` in `EngineConfig` as:
```
engine_config=EngineConfig(distributed=True, ...)
```
and 2) launching the training script with `torch.distributed.launch` on every node as standard PyTorch distributed training.

In the future, we plan to simplify the launching procedure as Microsoft's DeepSpeed or HuggingFace's Accelerate. To do this, we need to write a custom launcher code. If you are willing to contribute to this, that is very welcome!

I am sorry again for the delay, and let me know if you have any questions!

Best,
Sang
