### ISSUE TITLE
Any plan to support SAMA?

### ISSUE THREAD

**Issue by 1Konny** [leopard-ai/betty#20]
It would be really nice if betty supports SAMA as well! Thanks!

**Comment by sangkeun00** [comment]
@1Konny Thanks for your interest. [SAMA](https://github.com/leopard-ai/betty/blob/main/betty/hypergradient/sama.py) is already supported in Betty.

If your goal is to reproduce results in [Making Scalable Meta Learning Practical](https://arxiv.org/abs/2310.05674), you may use the following `Config` setup.

```python
from betty.configs import Config

# if your base-level optimizer is Adam or its variants
myconfig = Config(type="sama", sama_multitask=True)
# if your base-level optimizer is SGD. Even though its name is 'darts',
# our implementation follows SAMA instead of original DARTS. We will
# fix this naming in the future.
myconfig = Config(type="darts", darts_multitask=True)
```

Let me know if you have any additional questions.

Best,
Sang

**Comment by 1Konny** [comment]
I appreciate your quick reply. 

Oh, I should have double-checked that. I'll give it a try. Thanks!
