### ISSUE TITLE
[REQUEST] Documentation for MAML

### ISSUE THREAD

**Issue by sangkeun00** [leopard-ai/betty#3]
Need to write an example documentation for MAML.

**Comment by sangkeun00** [comment]
@jihoontack 

Thanks for your interest and congratulating words!
I will try to work on the MAML example documentation after I finish some code cleaning (I can potentially optimize memory usage a bit more from the current implementation).

Regarding using DDP for MAML-like experiments, depending on your setup, it may not be very useful especially if your goal is to apply MAML to larger neural networks.

More specifically, GPU memory usage in deep learning can largely be divided into two categories:
- Intermediate sates: intermediate activations for backpropagation, ...
- Parameters: model parameters, optimizer states, ...

The simplest DDP helps most with intermediate states memory by reducing the local batch size, and thereby activation memory, for each device.
However, in (the most basic) MAML, the batch size is very small due to its few-shot setting.
Thus, there is very little to gain from using DDP in the MAML setting.
I recommend rather using the ZeRO strategy which helps with parameter memory through optimizer state sharding.

If you have any questions/comments, feel free to let me know!

**Comment by jihoontack** [comment]
Thanks for the recommendation and for sharing the details!! I will definitely check out the ZeRO strategy!

I was recently working on using MAML on other domains (e.g., neural fields), where it quite often requires a large batch for stabilizing the training process. I think ZeRO will also be helpful in this scenario.

Thanks for your kind reply, and congrats again for publishing a nice paper :)

Best,
Jihoon

**Comment by sangkeun00** [comment]
Hello @jihoontack,

I just cleaned up our iMAML implementation with Betty, and also included the tutorial in our documentation website. For your convenience, here are:

- Tutorial: https://leopard-ai.github.io/betty/examples/maml.html
- Code: https://github.com/leopard-ai/betty/tree/main/examples/implicit_maml

Feel free to reach out to me if you have further questions!

Best,
Sang

**Comment by jihoontack** [comment]
Thank you so much for your contribution!

I will definitely cite and highlight the package when I have a chance to use it

Best,
Jihoon
