### ISSUE TITLE
WandB logging issue

### ISSUE THREAD

**Issue by asking28** [leopard-ai/betty#5]
wandb: (1) Create a W&B account
wandb: (2) Use an existing W&B account
wandb: (3) Don't visualize my results
wandb: Enter your choice: 2
wandb: You chose 'Use an existing W&B account'
wandb: Logging into wandb.ai. (Learn how to deploy a W&B server locally: https://wandb.me/wandb-server)
wandb: You can find your API key in your browser here: https://wandb.ai/authorize
wandb: Paste an API key from your profile and hit enter, or press ctrl+c to quit:
wandb: Appending key for api.wandb.ai to your netrc file: /root/.netrc
wandb: ERROR Error while calling W&B API: entity pod-tuning not found during upsertBucket (<Response [404]>)

**Comment by sangkeun00** [comment]
Hello @asking28,

Thanks for opening the issue. We haven't fully tested wandb logging yet, but will fix this in the near future.
I will leave an additional comment once this is added, and you can install the nightly version to use the feature!
If you are willing to work on this issue, that would be also very much appreciated!

**Comment by asking28** [comment]
@sangkeun00 thanks I'll try to work on that. Thanks for update.

**Comment by asking28** [comment]
@sangkeun00 
We are setting entity which corresponds to username or teamname, which is causing error in wandb logging. For now I have found this work around:
class WandBLogger(LoggerBase):
    def __init__(self):
        try:
            wandb.init(project="betty", entity=socket.gethostname())
        except:
            wandb.init(project="betty", reinit=True)

**Comment by sangkeun00** [comment]
@asking28 
Thanks for your work!
I will try your code, and after some testing, update the source code for this
